### ISSUE TITLE
Cash sending issue (incorrect JSON)

### ISSUE THREAD

**Issue by asluchevskiy** [vaklinov/zcash-swing-wallet-ui#4] opened 2016-10-31 20:53 UTC
Hi

Here is the screenshot
http://i.imgur.com/3x5uDCV.png

```
com.vaklinov.zcashui.ZCashClientCaller$WalletCallException: Error response from wallet: error: Error parsing JSON:[{"address":"t1K6oZpzk7vN3vAE1D3ThxdtsgBoVwMydok","amount":0,005}]

	at com.vaklinov.zcashui.ZCashClientCaller.sendCash(ZCashClientCaller.java:362)
	at com.vaklinov.zcashui.SendCashPanel.sendCash(SendCashPanel.java:450)
	at com.vaklinov.zcashui.SendCashPanel.access$000(SendCashPanel.java:75)
	at com.vaklinov.zcashui.SendCashPanel$1.actionPerformed(SendCashPanel.java:236)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

It looks like incorrect json, "," insted "." in floating number that was send to zcashd.

**Comment by vaklinov** [comment] 2016-10-31 21:17
Thank you for the bug report. Indeed there is an issue that the decimal format is formed using system Locale settings but it should be hard-coded dot (.) instead. Will be fixed ASAP.

**Comment by vaklinov** [comment] 2016-10-31 21:38
I have just fixed it in the latest version 0.33-beta. It would be nice if you build it again from source (latest master branch) and confirm that it works since I did not reproduce the problem on a system with my locale...

**Comment by asluchevskiy** [comment] 2016-10-31 22:03
Yes, it works: http://i.imgur.com/sVQZUge.png

Also, my locale was

```
$ locale
LANG=ru_RU.UTF-8
LANGUAGE=ru_RU:ru:en
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER="ru_RU.UTF-8"
LC_NAME="ru_RU.UTF-8"
LC_ADDRESS="ru_RU.UTF-8"
LC_TELEPHONE="ru_RU.UTF-8"
LC_MEASUREMENT="ru_RU.UTF-8"
LC_IDENTIFICATION="ru_RU.UTF-8"
LC_ALL=
```

**Comment by lavrfedotov** [comment] 2016-10-31 22:15
send me jar file please of 0.33
i dont understand github and lunix )
trying to rebuild 0.27, but have nothing

**Comment by vaklinov** [comment] 2016-10-31 22:24
@asluchevskiy Thank you very much for the test. Closing bug...

@lavrfedotov It is not recommended to use JARs sent over the net ;-) but as an exception I attach one:
[ZCashSwingWalletUI.jar.zip](https://github.com/vaklinov/zcash-swing-wallet-ui/files/562979/ZCashSwingWalletUI.jar.zip)

Still, I recommend this guide - explains how to build the wallet and can be followed by Linux beginners: https://www.cryptocompare.com/wallets/guides/how-to-install-the-zcash-gui-wallet

**Closed** 2016-10-31 22:26 UTC
Labels: bug
